# Generated by Django 2.2.9 on 2020-02-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='questions', to='languages.Language'),
        ),
    ]
