# Generated by Django 2.2.9 on 2020-02-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('jwt_auth', '0004_auto_20200226_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='users', to='languages.Language'),
        ),
    ]
