# Generated by Django 2.2.9 on 2020-02-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0005_user_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unseen_chat',
            field=models.BooleanField(default=False),
        ),
    ]
