# Generated by Django 2.2.9 on 2020-02-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_chat_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='unseen_message',
            field=models.BooleanField(default=False),
        ),
    ]
